theme: jekyll-theme-dinky
title: Italiano Con Turbo
description: Extra Interactive Practice

github:
  page2: corso.html
  page3: alfabeto.html
  page4: numeri.html
  page5: settimana.html
  page6: salutare.html
  page7: presentarsi.html
  page8: biography.html
  page9: challenge1.html
  page10: challenge2.html
